#!/usr/bin/env bash
# add & mod hostname's ip mappings
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
awk '$1=="127.0.0.1" && $2=="localhost" {$1="127.0.0.2"} 1' /etc/hosts | sudo tee /etc/hosts > /dev/null
