#!/usr/bin/env bash
# add & mod hostname's ip mappings
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
sudo sed -i "s/127.0.0.1 localhost/127.0.0.2 localhost/" /etc/hosts > /dev/null
